// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_njaa36L2Ld60jmfafJ5T7e56IWLpurM',
    appId: '1:605109648876:web:f1eabc870f842705ed94c9',
    messagingSenderId: '605109648876',
    projectId: 'authentication-c0a49',
    authDomain: 'authentication-c0a49.firebaseapp.com',
    storageBucket: 'authentication-c0a49.appspot.com',
    measurementId: 'G-NPMG37QKCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOScfviDB2EeKo3NNptbGPHsVI3-Vz9c',
    appId: '1:605109648876:android:907b03e58cc756eeed94c9',
    messagingSenderId: '605109648876',
    projectId: 'authentication-c0a49',
    storageBucket: 'authentication-c0a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ouOFrqH6Od5K_PTylSn_Vdn4Ex6pZE0',
    appId: '1:605109648876:ios:f6ba3b292db55c4eed94c9',
    messagingSenderId: '605109648876',
    projectId: 'authentication-c0a49',
    storageBucket: 'authentication-c0a49.appspot.com',
    iosClientId: '605109648876-squdkrnoqsg90m218hu50unrn0pf1am4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ouOFrqH6Od5K_PTylSn_Vdn4Ex6pZE0',
    appId: '1:605109648876:ios:fc1e4f1e2cbe2745ed94c9',
    messagingSenderId: '605109648876',
    projectId: 'authentication-c0a49',
    storageBucket: 'authentication-c0a49.appspot.com',
    iosClientId: '605109648876-4rhh7o8ni161bhudblpdgdn37951plu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
